# Generated by Django 5.2.15 on 2026-07-31 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_category_options_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['renewal_date'], 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('RENEWED', 'Renewed'), ('CANCELLED', 'Cancelled'), ('RESTORED', 'Restored')], max_length=20)),
                ('old_renewal_date', models.DateField(blank=True, null=True)),
                ('new_renewal_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name_plural': 'Subscription History',
                'ordering': ['-created_at'],
            },
        ),
    ]
